meetpy/meetpy/urls.py
from django.conf import settings
from django.urls import include, path, re_path
from django.conf.urls.static import static
from django.contrib import admin

admin.autodiscover()

urlpatterns = [
    path('', include(('misc.urls', 'misc'), namespace='misc')),
    path('', include(('meetups.urls', 'meetups'), namespace='meetups')),
    re_path(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

meetpy/meetups/urls.py
from django.urls import path, re_path
from django.urls import reverse_lazy
from django.views import generic

from . import views

urlpatterns = [
    path('spotkania/', views.MeetupsListView.as_view(), name='meetup_list'),
    re_path(r'^(?P<meetup_type>[\w-]+)/(?P<number>\d+)/$',
        views.MeetupDetailView.as_view(), name='meetup_detail'),
    path('<int:number>/', views.MeetupRedirectOrList.as_view(),
        name='meetup_redirect_or_list'),
    re_path(r'^(?P<meetup_type>[\w-]+)/(?P<number>\d+)/promo/$', views.MeetupPromoView.as_view(), name='meetup_promo'),
    path('sponsorzy/', views.SponsorListView.as_view(), name='sponsor_list'),
    path('prelegenci/', views.SpeakerListView.as_view(), name='speaker_list'),
    path('zgloszenie/', views.TalkProposalCreateView.as_view(), name='talk_proposal'),
    path('zgloszenie/potwierdzenie/', views.TalkProposalConfirmationView.as_view(), name='talk_proposal_confirmation'),
    path('atom/', views.MeetupsAtomFeed(), name='atom_feed'),
    path('rss/', views.MeetupsRssFeed(), name='rss_feed'),

    # Legacy URL's from old website
    path('historia/', generic.RedirectView.as_view(url=reverse_lazy('meetups:meetup_list'), permanent=True)),
    re_path(r'^(?P<day>\d{2})-(?P<month>\d{2})-(?P<year>\d{4})/$', views.MeetupDateRedirectView.as_view(permanent=True), name='date_redirect'),
    path('home/sponsor/', generic.RedirectView.as_view(url=reverse_lazy('meetups:sponsor_list'), permanent=True)),
    path('home/poradnik-prelegenta', generic.RedirectView.as_view(url=reverse_lazy('meetups:speaker_list'), permanent=True)),
]

meetpy/misc/urls.py
from django.urls import path, re_path
from django.contrib.sitemaps.views import sitemap

from . import views
from .sitemaps import sitemaps

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('faq/', views.FaqView.as_view(), name='faq'),
    path('discord/', views.discord_invite, name="discord"),
    re_path(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}),
]

meetpy/misc/models.py
import os
from django.conf import settings
from django.db import models
from django.utils.deconstruct import deconstructible
from django.utils.text import slugify


@deconstructible
class SlugifyUploadTo(object):

    def __init__(self, path, fields):
        self.path = path
        self.fields = fields

    def __call__(self, instance, filename):
        extension = filename.split('.')[-1]
        slug = slugify(' '.join([str(getattr(instance, field)) for field in self.fields]))
        new_filename = '{0}.{1}'.format(slug, extension)
        return os.path.join(self.path, new_filename)


class Partner(models.Model):
    name = models.CharField(max_length=200)
    url = models.URLField()
    logo = models.FileField(upload_to=SlugifyUploadTo(settings.PARTNER_LOGOS_DIR, ['name']))
    is_public = models.BooleanField()

    def __str__(self):
        return self.name

meetpy/misc/views.py
import datetime

from django.views import generic
from django.shortcuts import redirect
from django.conf import settings

from meetups import models as meetups_models
from . import models


class HomeView(generic.TemplateView):
    template_name = 'misc/home.html'

    def get_context_data(self):
        context = super().get_context_data()
        today = datetime.date.today()
        try:
            context['upcoming_meetup'] = meetups_models.Meetup.objects.get_upcoming(today)
        except meetups_models.Meetup.DoesNotExist:
            context['upcoming_meetup'] = None
        context['partners'] = models.Partner.objects.filter(is_public=True)
        context["previous_meetups"] = meetups_models.Meetup.objects.past(today)[:3]
        return context


class FaqView(generic.TemplateView):
    template_name = 'misc/faq.html'


def discord_invite(request):
    return redirect(settings.DISCORD_INVITE)

meetpy/templates/misc/faq.html
{% extends "base_content.html" %}

{% load static %}

{% block title %}FAQ{% endblock %}

{% block og_title %}FAQ{% endblock %}

{% block subcontent %}
    <div class="margin-bottom-large faq">
        <h1>FAQ</h1>
        <ol class="page-menu margin-bottom-large">
            <li><a href="#for-attendees">Dla uczestników</a></li>
            <li><a href="#for-speakers">Dla prelegentów</a></li>
            <li><a href="#for-sponsors">Dla sponsorów</a></li>
            <li><a href="#for-partners">Dla partnerów</a></li>
        </ol>
        <div id="for-speakers">
            <h2>Dla prelegentów</h2>
            <h3>Jak się zgłosić?</h3>
                <p>Prosimy przesyłać propozycję prezentacji za pomocą <a href="{% url "meetups:talk_proposal" %}">formularza zgłoszeniowego</a>.</p>
            <h3>Ile czasu będzie przeznaczone na moją prezentację?</h3>
                <p>Standardowo jedna prezentacja trwa około {{ group.presentation_length }} minut. Staramy się pilnować wyznaczonego czasu i po jego przekroczeniu będziemy prosić prelegenta o jak najszybsze zakończenie wystąpienia. Na jednym spotkaniu odbywają się maksimum 3 prezentacje.</p>
            <h3>Co powinienem zrobić w dniu prezentacji?</h3>
                <p>Prosimy prelegentów o przybycie minimum 15 minut przed rozpoczęciem spotkania, abyśmy mogli rozwiązać potencjalne problemy np. z podłączeniem laptopa do rzutnika czy internetu.</p>
            <h3>Co powinienem zrobić po prezentacji?</h3>
                <p>Prosimy o przesłanie nam materiałów prezentowanych podczas prelekcji (np. slajdy, kod) abyśmy mogli umieścić je na podstronie spotkania.</p>
            <h3>Czy dozwolone są prezentacje reklamujące komercyjne produkty lub ogłoszenia rekrutacyjne?</h3>
                <p>Takie prezentacje nie są wpisywane do agendy, ale po głównych prezentacjach mamy czas przeznaczony na tego typu krótkie ogłoszenia. Prosimy poinformować nas przed spotkaniem o chęci wystąpienia.</p>
        </div>
        <div id="for-attendees" class="margin-top-big">
            <h2>Dla uczestników</h2>
            <h3>W jakim języku odbywają się spotkania?</h3>
                <p>Większość prezentacji prowadzona jest w języku polskim, w tym języku prowadzimy też spotkanie. Zdarzają się jednak prezentacje w języku angielskim - zostają one odpowiednio oznaczone w agendzie.</p>
            <h3>Jak wyglądają spotkania {{ group.name }}?</h3>
                <p>W ramach spotkań odbywają się 2-3 prezentacje związane z Pythonem i ogólnie IT. Następnie większość uczestników zostaje na networking przy piwie.</p>
        </div>
        <div id="for-sponsors" class="margin-top-big">
            <h2>Dla sponsorów</h2>
            <h3>Jak zostać sponsorem?</h3>
                <p>Prosimy o kontakt mailowy na {{ group.email }} gdzie omówimy szczegóły.</p>
            <h3>Na co mogę liczyć jako sponsor?</h3>
                <p>Sponsor naszych spotkań może liczyć na:</p>
                <ul>
                    <li>umieszczenie loga sponsora na głównej stronie {{ group.name }} obok zapowiadanego spotkania,</li>
                    <li>umieszczenie loga sponsora na podstronie spotkania,</li>
                    <li>umieszczenie loga i opisu sponsora na podstronie “Sponsorzy”,</li>
                    <li>wymienienie jako sponsor spotkania podczas zapowiedzi spotkania przez organizatorów,</li>
                    <li>pojawienia się specjalnej notki o sponsorze spotkania w mediach społecznościowych (Facebook/Twitter),</li>
                    <li>umieszczenie swojego baneru w sali spotkania.</li>
                </ul>
            <h3>Jaki rodzaj sponsoringu preferujemy?</h3>
                <p>W zależności od rodzaju spotkania:</p>
                <ul>
                    <li>zakup napojów i jedzenia dla uczestników spotkania,</li>
                    <li>pokrycie kosztów związanych z przejazdem i pobytem w {{ group.city_ablative }} zaproszonego prelegenta,</li>
                    <li>ufundowanie drobnych podarunków (np. książki) rozlosowanych podczas spotkania.</li>
                </ul>
            <h3>Jak wygląda rozliczenie sponsoringu?</h3>
                <p>{{ group.name }} nie wystawia faktur VAT.</p>
        </div>
        <div id="for-partners" class="margin-top-big">
            <h2>Dla partnerów</h2>
            <h3>Kto może zostać partnerem?</h3>
            <p>Partnerem {{ group.name }} może zostać dowolna inicjatywa, organizacja lub firma, jednak preferowane są działalności:</p>
            <ul>
                <li>niekomercyjne,</li>
                <li>poświęcone w głównej mierze językowi Python i jego środowisku,</li>
                <li>prowadzone w {{ group.city_ablative }}.</li>
            </ul>
            <h3>Jak zostać partnerem?</h3>
            <p>Prosimy o kontakt mailowy na <a href="mailto:{{ group.email }}">{{ group.email }}</a>. W korespondencji prosimy o zawarcie informacji o:</p>
            <ul>
                <li>powiązaniu partnera z językiem Python i jego środowiskiem,</li>
                <li>kosztach uczestnictwa (jeżeli dotyczy),</li>
                <li>treściach marketingowych potrzebnych do promocji, np. szablon postu jaki miałby zostać opublikowany na naszych kanałach społecznościowych, logotyp inicjatywy, etc. (jeżeli dotyczy).</li>
                <li>proponowanych profitach dla społeczności {{ group.name }} płynących z partnerstwa.</li>
            </ul>
            <h3>Na co mogę liczyć jako partner?</h3>
            <p>Partner naszej inicjatywy może liczyć na:</p>
            <ul>
                <li>umieszczenie loga partnera na głównej stronie {{ group.name }} (sekcja partnerzy),</li>
                <li>promocja wydarzeń lub produktów partnera podczas zapowiedzi spotkania przez organizatorów,</li>
                <li>promocja wydarzeń lub produktów partnera na naszych kanałach social media.</li>
            </ul>
            <h3>Czego oczekuje {{ group.name }} w zamian za nawiązanie partnerstwa?</h3>
            <p>Zależy to od rodzaju współpracy, ale najczęściej jest to:</p>
            <ul>
                <li>umieszczenie naszego logotypu na stronie partnera,</li>
                <li>promocja wydarzeń organizowanych przez {{ group.name }} na kanałach społecznościowych partnera,</li>
                <li>wejściówka na wydarzenie/egzemplarz produktu partnera/kod rabatowy dla uczestników naszych spotkań.</li>
            </ul>
            <h3>Gdzie znajdę materiały promocyjne {{ group.name }}?</h3>
            <ul>
                <li>opis - <a href="#description-pl" data-toggle="modal">PL</a>, <a href="#description-en" data-toggle="modal">EN</a></li>
                <li>logotyp - <a href="{% static group.logo %}" target="_blank">PNG</a></li>
            </ul>

            <div id="description-pl" class="modal hide fade" tabindex="-1" role="dialog" aria-hidden="true">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h3>Opis {{ group.name }} - PL</h3>
                </div>
                <div class="modal-body">
                    <p>
                        {{ group.name }} to spotkania {{ group.city_locative }} społeczności Pythonistów. Głównym założeniem inicjatywy jest wymiana doświadczeń w trybie face2face i przelanie energii pasjonatów tego dynamicznego języka programowania w konkretne działania dla dobra ludzkości.
                    </p>
                </div>
            </div>

            <div id="description-en" class="modal hide fade" tabindex="-1" role="dialog" aria-hidden="true">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h3>Opis {{ group.name }} - EN</h3>
                </div>
                <div class="modal-body">
                    <p>{{ group.name }} is a community that gathers Python hobbyists from {{ group.city }} and its surroundings.</p>
                </div>
            </div>

        </div>
    </div>
{% endblock %}

meetpy/templates/misc/home.html
{% extends "base.html" %}

{% load static  embed_video_tags %}

{% block title %}Home{% endblock %}

{% block og_title %}Home{% endblock %}

{% block js %}
{% include 'includes/maps_api_script.html' with canvas_id='map-canvas' latitude=upcoming_meetup.venue.latitude longitude=upcoming_meetup.venue.longitude zoom=15 disable_ui=1 %}
{% endblock %}

{% block content %}
<div class="container">
    {% if upcoming_meetup %}
    <div class="row">
        <div class="span2 img-tip">
            <div class="line-orange"></div>
        </div>
        <div class="span10">
            <h1><a href="{{ upcoming_meetup.get_absolute_url }}">Następne spotkanie {{ upcoming_meetup }}</a></h1>
        </div>
    </div>
    <div class="row">
        <div class="span5 offset2">
            <h4 class="date"><span class="day">{{ upcoming_meetup.date|date:"l" }}, </span>{{ upcoming_meetup.date|date:"d.m.Y" }} <span class="pull-right"><i class="icon-clock"></i> {{ upcoming_meetup.date|date:"H:i" }}</span></h4>
            {% if upcoming_meetup.venue %}
            <h5 class="location"><img src="{% static 'img/location.png' %}" alt="Lokalizacja" class="icon-location-home"> {{ upcoming_meetup.venue.name }}, {{ upcoming_meetup.venue.address }}</h5>
            <div class="text-center">
                <div class="clearfix">
                    <div class="map" id="map-canvas"></div>
                </div>
                <a href="{{ upcoming_meetup.get_absolute_url }}" class="button button-block margin-top-normal more">WIĘCEJ INFORMACJI</a>
            </div>
            {% endif %}
        </div>
        <div class="span5 box-users">
            {% if upcoming_meetup.meetup_type.has_agenda %}
              {% for talk in upcoming_meetup.talks.all %}
              <div class="row">
                  <div class="span1">
                    {% if talk.speakers.count == 1 %}
                    <img src="{% if talk.speakers.get.photo %}{{ talk.speakers.get.photo.url }}{% else %}{% static 'img/avatar.png' %}{% endif %}" alt="Zdjęcie {{ speaker }}" class="img-user">
                    {% else %}
                    <div class="carousel slide" id="myCarousel">
                      <div class="carousel-inner">
                        {% for speaker in talk.speakers.all %}
                        <img src="{% if speaker.photo %}{{ speaker.photo.url }}{% else %}{% static 'img/avatar.png' %}{% endif %}" alt="Zdjęcie {{ speaker }}" class="img-user item">
                        {% endfor %}
                        </div>
                    </div>
                      {% endif %}
                  </div>
                  <div class="span4 link-grey">
                      <h5>
                      {% for speaker in talk.speakers.all %}
                          <a class="link-grey" href="{{ upcoming_meetup.get_absolute_url }}#speaker-{{ speaker|slugify }}">{{ speaker }}</a>{% if not forloop.last %}, {% endif %}
                      {% endfor %}
                      </h5>
                      <p class="text-smaller"><a href="{{ upcoming_meetup.get_absolute_url }}#talk-{{ talk|slugify }}">{{ talk.title }}</a></p>
                  </div>
              </div>
              {% endfor %}
              {% if not upcoming_meetup.is_ready %}
              <div class="more-info">
                <h3>agenda w przygotowaniu</h3>
              </div>
              {% endif %}
            {% else %}
              <div class="row">
                <div class="span6">
                  {{ upcoming_meetup.description_md }}
                </div>
              </div>
            {% endif %}
        </div>
    </div>

      {% if upcoming_meetup.video_url %}
      <div class="row">
        <div class="span10 offset2 margin-top-normal">
          <div class="video-meetup-details">
            {% video upcoming_meetup.video_url '780x440' is_secure=True %}
          </div>
        </div>
      </div>
      {% endif %}

    {% if upcoming_meetup.sponsors.exists %}
    <div class="row">
        <div class="span10 offset2 margin-top-normal">
            <h3 class="span2 text-sponsors text-left">SPONSORZY:</h3>
            <div class="row-fluid">
                <div class="sponsors">
                    <table class="row-fluid home-sponsors-table">
                        <tr>
                            {% for sponsor in upcoming_meetup.sponsors.all %}
                            <td>
                                <a href="{{ sponsor.website }}" target="_blank" class="no-hover">
                                    <img src="{{ sponsor.logo.url }}" alt="{{ sponsor.name }}">
                                </a>
                            </td>
                            {% if forloop.counter|divisibleby:4 %}</tr><tr>{% endif %}
                            {% endfor %}
                        </tr>
                    </table>
                    <div class="home-sponsors-mobile">
                        {% for sponsor in upcoming_meetup.sponsors.all %}
                        <div>
                            <a href="{{ sponsor.website }}" target="_blank" class="no-hover">
                                <img src="{{ sponsor.logo.url }}" alt="{{ sponsor.name }}">
                            </a>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endif %}
    {% else %}
    <div class="more-info">
        <h3>spotkanie w przygotowaniu</h3>
    </div>
    {% endif %}
</div>
<div class="container">
    <div class="row talk-proposal-landing">
        <p class="span6 offset2 talk-proposal-description">Chcesz wystąpić na kolejnym spotkaniu {{ group.name }}? Zgłoś się już teraz!</p>
        <p class="span4"><a href="{% url "meetups:talk_proposal" %}" class="button button-block talk-proposal-button"><span class="plus-icon">+</span>Zgłoś prelekcję</a></p>
    </div>
</div>
<div class="box-home">
    <div class="container">
        <div class="row">
            <div class="span2 img-tip">
                <img src="{% static 'img/question.jpg' %}" alt="Informacje">
            </div>
            <div class="span10">
                <h2>{{ group.city_adjective }} grupa użytkowników Pythona</h2>
                <div class="row">
                  <div class="video-landing">
{#                    <iframe width="800" height="410" src="http://www.youtube.com/embed/Rrbpnrs8neM" frameborder="0" allowfullscreen></iframe>#}
                  </div>
                </div>
                <div class="row">
                    <div class="span5">
                        <p> {{ group.name }} to spotkania {{ group.city_locative }} społeczności Pythonistów.
                            Głównym założeniem inicjatywy jest wymiana doświadczeń w trybie face2face i
                            przelanie energii pasjonatów tego dynamicznego języka programowania w konkretne działania dla dobra ludzkości.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% if partners %}
<div class="container">
    <div class="row">
        <div class="span10 offset2 margin-top-big margin-bottom-big">
            <h2>Partnerzy</h2>
            <div class="row-fluid">
                <div class="pull-left">
                    {% for partner in partners %}
                    <a href="{{ partner.url }}" title="{{ partner.name }}" class="no-hover" target="_blank">
                        <img class="partner-logo" src="{{ partner.logo.url }}" alt="{{ partner.name }}">
                    </a>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endif %}
{% if previous_meetups %}
<div class="container">
    <div class="row">
        <div class="span2 img-tip margin-top-big">
            <div class="line-orange"></div>
        </div>
        <div class="span10 margin-top-big">
          <h2>Poprzednie spotkania</h2>
          {% for meetup in previous_meetups %}
          {% include "meetups/includes/meetup_on_list.html" %}
          {% endfor %}
        </div>
    </div>
</div>
{% endif %}
<script>
$('.carousel img:first-child').addClass('active');
$('.carousel').carousel();
</script>
{% endblock %}