meetpy/meetpy/urls.py
from django.conf import settings
from django.urls import include, path, re_path
from django.conf.urls.static import static
from django.contrib import admin

admin.autodiscover()

urlpatterns = [
    path('', include(('misc.urls', 'misc'), namespace='misc')),
    path('', include(('meetups.urls', 'meetups'), namespace='meetups')),
    re_path(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

meetpy/meetups/urls.py
from django.urls import path, re_path
from django.urls import reverse_lazy
from django.views import generic

from . import views

urlpatterns = [
    path('spotkania/', views.MeetupsListView.as_view(), name='meetup_list'),
    re_path(r'^(?P<meetup_type>[\w-]+)/(?P<number>\d+)/$',
        views.MeetupDetailView.as_view(), name='meetup_detail'),
    path('<int:number>/', views.MeetupRedirectOrList.as_view(),
        name='meetup_redirect_or_list'),
    re_path(r'^(?P<meetup_type>[\w-]+)/(?P<number>\d+)/promo/$', views.MeetupPromoView.as_view(), name='meetup_promo'),
    path('sponsorzy/', views.SponsorListView.as_view(), name='sponsor_list'),
    path('prelegenci/', views.SpeakerListView.as_view(), name='speaker_list'),
    path('zgloszenie/', views.TalkProposalCreateView.as_view(), name='talk_proposal'),
    path('zgloszenie/potwierdzenie/', views.TalkProposalConfirmationView.as_view(), name='talk_proposal_confirmation'),
    path('atom/', views.MeetupsAtomFeed(), name='atom_feed'),
    path('rss/', views.MeetupsRssFeed(), name='rss_feed'),

    # Legacy URL's from old website
    path('historia/', generic.RedirectView.as_view(url=reverse_lazy('meetups:meetup_list'), permanent=True)),
    re_path(r'^(?P<day>\d{2})-(?P<month>\d{2})-(?P<year>\d{4})/$', views.MeetupDateRedirectView.as_view(permanent=True), name='date_redirect'),
    path('home/sponsor/', generic.RedirectView.as_view(url=reverse_lazy('meetups:sponsor_list'), permanent=True)),
    path('home/poradnik-prelegenta', generic.RedirectView.as_view(url=reverse_lazy('meetups:speaker_list'), permanent=True)),
]

meetpy/misc/urls.py
from django.urls import path, re_path
from django.contrib.sitemaps.views import sitemap

from . import views
from .sitemaps import sitemaps

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('faq/', views.FaqView.as_view(), name='faq'),
    path('discord/', views.discord_invite, name="discord"),
    re_path(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}),
]

meetpy/templates/base.html
<!DOCTYPE html>{% load static i18n %}
<html lang="pl">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <title>{{ group.name }} | {% block title %}{% endblock %}</title>
    <meta name="keywords" content="{{ group.name }}, Python, grupa użytkowników, programowanie, barcamp, spotkanie, prezentacje">
    <meta name="description" content="{{ group.name }} to cykliczne spotkania pasjonatów języka programowania Python z {{ group.city_genitive }} i okolic.">

    <meta property="og:type" content="website">
    <meta property="og:title" content="{{ group.name }} | {% block og_title %}{% endblock %}"/>
    <meta property="og:description" content="{{ group.name }} to cykliczne spotkania pasjonatów języka programowania Python z {{ group.city_genitive }} i okolic.">
    <meta property="og:url" content="http://{{ site.domain }}{{ request.get_full_path }}">
    <meta property="og:image" content="http://{{ site.domain }}{% static 'img/logo.png' %}"/>
    <meta property="og:site_name" content="{{ group.name }}"/>


    <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,300,700&amp;subset=latin,latin-ext" rel="stylesheet" type="text/css">
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap-responsive.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/style-responsive.css' %}" rel="stylesheet">
    <link rel="alternate" type="application/rss+xml" href="{% url 'meetups:rss_feed' %}" />
    <link rel="alternate" type="application/atom+xml" href="{% url 'meetups:atom_feed' %}" />
    {% block css %}
    {% endblock %}
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <!--[if lt IE 9]>
    <script src="{% static 'js/html5shiv.js' %}"></script>
    <script src="{% static 'js/respond.src.js' %}"></script>
    <![endif]-->
    {% block js %}
    {% endblock %}
    <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
    ga('create', 'UA-17174483-2');
    ga('send', 'pageview');
    </script>
</head>
<body>
	<div id="wrapper">
		<header>
            <form action="{% url 'set_language' %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="next" value="{{ request.path }}">
                <select name="language" onchange="this.form.submit()">
                    {% get_current_language as current_language %}
                    {% get_available_languages as available_languages %}
                    {% for lang_code, lang_name in available_languages %}
                        <option value="{{ lang_code }}" {% if lang_code == current_language %}selected{% endif %}>
                            {{ lang_name }}
                        </option>
                    {% endfor %}
                </select>
            </form>
			<div class="container">
				<div class="row">
					<div id="header-logo" class="span2">
						<a href="{% url 'misc:home' %}"><img src="{% static 'img/logo.png' %}" alt="{{ group.name }}" class="logo"></a>
					</div>
					<div id="top">
						<div class="span7">
							<ul class="menu-top">
                {% url 'meetups:meetup_list' as meetup_list_url %}
                {% url 'meetups:speaker_list' as speaker_list_url %}
                {% url 'meetups:sponsor_list' as sponsor_list_url %}
                {% url 'misc:home' as home_url %}
                {% url 'misc:faq' as faq_url %}
                <li><a href="{{ home_url }}"{% if request.path == home_url %} class="active"{% endif %}>Home</a></li>
								<li><a href="{{ meetup_list_url }}"{% if request.path == meetup_list_url %} class="active"{% endif %}>Spotkania</a></li>
                <li><a href="{{ speaker_list_url }}"{% if request.path == speaker_list_url %} class="active"{% endif %}>Prelegenci</a></li>
                <li><a href="{{ sponsor_list_url }}"{% if request.path == sponsor_list_url %} class="active"{% endif %}>Sponsorzy</a></li>
                <li><a href="{{ faq_url }}"{% if request.path == faq_url %} class="active"{% endif %}>FAQ</a></li>
							</ul>
						</div>
						<div class="span3">
							<div class="top-links">
                {% if group.social.slack %}
                                <a href="{{ group.social.slack }}" class="slack" target="_blank" title="Slack"></a>
                {% endif %}
                {% if group.social.discord %}
                  <a href="{{ group.social.discord }}" class="discord" target="_blank" title="Discord"></a>
                {% endif %}
                {% if group.social.meetup %}
  								<a href="{{ group.social.meetup }}" class="meetup" target="_blank"></a>
                {% endif %}
                {% if group.social.facebook %}
		  						<a href="{{ group.social.facebook }}" class="facebook" target="_blank"></a>
                {% endif %}
                {% if group.social.twitter %}
	  							<a href="{{ group.social.twitter }}" class="twitter" target="_blank"></a>
                {% endif %}
                {% if group.social.youtube %}
  								<a href="{{ group.social.youtube }}" class="youtube" target="_blank"></a>
                {% endif %}
								<div class="dropdown pull-right">
								    <a href="#" data-toggle="dropdown" class="dropdown-toggle rss" role="button" id="drop1"></a>
								    <ul aria-labelledby="drop1" role="menu" class="dropdown-menu">
	                    <li role="presentation"><a href="{% url 'meetups:rss_feed' %}" tabindex="-1" role="menuitem" target="_blank">RSS</a></li>
	                    <li role="presentation"><a href="{% url 'meetups:atom_feed' %}" tabindex="-1" role="menuitem" target="_blank">Atom</a></li>
			              </ul>
			          </div>
								<a href="mailto:{{ group.email }}" class="mail"></a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</header>
        {% block content %}
        {%  endblock %}
		<div id="push"></div>
	</div>
	<footer>
		<div class="container">
			<div class="row">
                <div class="span12">
                    <div class="row margin-bottom-large">
                        <div class="span2">
                            <h5>Mapa witryny</h5>
                            <ul>
                                <li><a href="{% url 'misc:home' %}">Home</a></li>
                                <li><a href="{% url 'meetups:meetup_list' %}">Spotkania</a></li>
                                <li><a href="{% url 'meetups:speaker_list' %}">Prelegenci</a></li>
                                <li><a href="{% url 'meetups:sponsor_list' %}">Sponsorzy</a></li>
                                <li><a href="{% url 'misc:faq' %}">FAQ</a></li>
                            </ul>
                        </div>
                        <div class="span2">
                            <h5>Jesteśmy na</h5>
                            <ul class="social-media-footer">
                                {% if group.social.meetup %}
                                    <li><a href="{{ group.social.meetup }}" class="meetup" target="_blank"></a></li>
                                {% endif %}
                                {% if group.social.facebook %}
                                    <li><a href="{{ group.social.facebook }}" class="facebook" target="_blank"></a></li>
                                {% endif %}
                                {% if group.social.twitter %}
                                    <li><a href="{{ group.social.twitter }}" class="twitter" target="_blank"></a></li>
                                {% endif %}
                                {% if group.social.youtube %}
                                    <li><a href="{{ group.social.youtube }}" class="youtube" target="_blank"></a></li>
                                {% endif %}
                            </ul>
                        {% if group.social.slack %}
                            <a href="{{ group.social.slack }}" class="slack-footer">
                                <i class="slack-icon"></i>
                                <span>Join Slack</span>
                            </a>
                        {% endif %}
                        {% if group.social.discord %}
                          <a href="{{ group.social.discord }}" class="discord-footer">
                            <i class="discord-icon"></i>
                            <span>Join discord</span>
                          </a>
                        {% endif %}
                        </div>
                        <div class="span2">
                            <h5>Python w Polsce</h5>
                            <ul>
                                <li><a href="http://pl.python.org/" target="_blank">PPCG</a></li>
                                <li><a href="http://pl.pycon.org/" target="_blank">PyCon PL</a></li>
                                <li><a href="http://poland.pyladies.com" target="_blank">Pyladies Poland</a></li>
                                <li><a href="http://pywaw.org/" target="_blank">PyWaw</a></li>
                                <li><a href="http://pykonik.org/" target="_blank">Pykonik</a></li>
                            </ul>
                        </div>
                        <div class="span2">
                            <h5>&nbsp;</h5>
                            <ul>
                                <li><a href='http://pylight.org'>PyLight WAW</a></li>
                                <li><a href='https://www.facebook.com/pylightkrk/'>PyLight KRK</a></li>
                                <li><a href="http://pystok.org" target="_blank">PyStok</a></li>
                                <li><a href="http://pysilesia.pl/" target="_blank">PySilesia</a></li>
                                <li><a href="https://pythonlodz.org" target="_blank">Python Łódź</a></li>
                            </ul>
                        </div>
                        <div class="span2">
                            <h5>&nbsp;</h5>
                            <ul>
                                <li><a href="https://www.meetup.com/PyGda-pl/" target="_blank">PyGDA</a></li>
                                <li><a href="https://www.meetup.com/PyRa-Poznan-Python-Programmers/" target="_blank">PyRa</a></li>
                                <li><a href="https://www.facebook.com/WroclawPythonUserGroup" target="_blank">wroc.py</a></li>
                                <li><a href="https://pylove.org" target="_blank">PyLove</a></li>
                            </ul>
                        </div>
                        <div class="span2">
                            <h5>&nbsp;</h5>
                            <ul>
                                <li><a href='https://www.meetup.com/PyData-Warsaw/'>PyData Warsaw</a></li>
                                <li><a href='https://www.meetup.com/PyData-Krakow/'>PyData Kraków</a></li>
                                <li><a href='https://www.meetup.com/PyData-Wroclaw/'>PyData Wrocław</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="row">
                        <div class="span10">
                            <div class="pull-left statistics">
                                <h5 class="pull-left">Statystyki</h5>
                                <p class="pull-left">
                                Spotkania: <span>{{ meetups_stats.meetups_count }}</span>
                                &bull; Prelegenci: <span>{{ meetups_stats.speakers_count }}</span>
                                &bull; Prezentacje: <span>{{ meetups_stats.talks_count }}</span>
                                </p>
                            </div>
                            <div class="pull-left stack margin-left-big">
                                <h5 class="pull-left">Stack</h5>
                                <p class="pull-left">Python {{ system.python }} &bull; Django {{ system.django }} &bull; <a href="{{ group.github }}/tree/{{ system.website }}" target="_blank">@{{ system.website|slice:":5" }}</a></p>
                            </div>
                        </div>
                    </div>
                    <div class="row margin-bottom-small">
                        <div class="span10 margin-top-small">
                            <div class="powered">Powered by <a href="https://deployed.pl" target="_blank"><img id="footer-logo" src="{% static 'img/deployed.png' %}" alt="Powered by Deployed.pl"></a> Project by <a href="http://pywaw.org/">PyWaw</a></div>
                        </div>
                    </div>
                </div>
			</div>
		</div>
	</footer>
</body>
</html>

meetpy/templates/base_content.html
{% extends "base.html" %}


{% block content %}
<div class="container">
    <div class="row">
        <div class="span2 img-tip">
            <div class="line-orange"></div>
        </div>
        <div class="span10">
            {% block subcontent %}
            {% endblock %}
        </div>
    </div>
</div>
{% endblock %}