meetpy/meetpy/urls.py
from django.conf import settings
from django.urls import include, path, re_path
from django.conf.urls.static import static
from django.contrib import admin

admin.autodiscover()

urlpatterns = [
    path('', include(('misc.urls', 'misc'), namespace='misc')),
    path('', include(('meetups.urls', 'meetups'), namespace='meetups')),
    re_path(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

meetpy/meetups/urls.py
from django.urls import path, re_path
from django.urls import reverse_lazy
from django.views import generic

from . import views

urlpatterns = [
    path('spotkania/', views.MeetupsListView.as_view(), name='meetup_list'),
    re_path(r'^(?P<meetup_type>[\w-]+)/(?P<number>\d+)/$',
        views.MeetupDetailView.as_view(), name='meetup_detail'),
    path('<int:number>/', views.MeetupRedirectOrList.as_view(),
        name='meetup_redirect_or_list'),
    re_path(r'^(?P<meetup_type>[\w-]+)/(?P<number>\d+)/promo/$', views.MeetupPromoView.as_view(), name='meetup_promo'),
    path('sponsorzy/', views.SponsorListView.as_view(), name='sponsor_list'),
    path('prelegenci/', views.SpeakerListView.as_view(), name='speaker_list'),
    path('zgloszenie/', views.TalkProposalCreateView.as_view(), name='talk_proposal'),
    path('zgloszenie/potwierdzenie/', views.TalkProposalConfirmationView.as_view(), name='talk_proposal_confirmation'),
    path('atom/', views.MeetupsAtomFeed(), name='atom_feed'),
    path('rss/', views.MeetupsRssFeed(), name='rss_feed'),

    # Legacy URL's from old website
    path('historia/', generic.RedirectView.as_view(url=reverse_lazy('meetups:meetup_list'), permanent=True)),
    re_path(r'^(?P<day>\d{2})-(?P<month>\d{2})-(?P<year>\d{4})/$', views.MeetupDateRedirectView.as_view(permanent=True), name='date_redirect'),
    path('home/sponsor/', generic.RedirectView.as_view(url=reverse_lazy('meetups:sponsor_list'), permanent=True)),
    path('home/poradnik-prelegenta', generic.RedirectView.as_view(url=reverse_lazy('meetups:speaker_list'), permanent=True)),
]

meetpy/misc/urls.py
from django.urls import path, re_path
from django.contrib.sitemaps.views import sitemap

from . import views
from .sitemaps import sitemaps

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('faq/', views.FaqView.as_view(), name='faq'),
    path('discord/', views.discord_invite, name="discord"),
    re_path(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}),
]

meetpy/meetups/models.py
import datetime

from django.conf import settings
from django.urls import reverse
from django.db import models
from django.utils.html import escape
from django.utils.safestring import mark_safe
from markdown import markdown

from misc.models import SlugifyUploadTo


class Sponsor(models.Model):
    name = models.CharField(max_length=100)
    website = models.URLField()
    logo = models.ImageField(upload_to=settings.SPONSOR_LOGOS_DIR)
    description = models.TextField(blank=True)

    @property
    def description_md(self):
        return mark_safe(markdown(escape(self.description)))

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']


class Venue(models.Model):
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=200)
    longitude = models.DecimalField(max_digits=9, decimal_places=6)
    latitude = models.DecimalField(max_digits=9, decimal_places=6)

    def __str__(self):
        return self.name


class MeetupManager(models.Manager):

    def get_upcoming(self, date=None):
        date = date or datetime.date.today()
        try:
            return self.filter(date__gte=date).order_by('date')[0]
        except IndexError:
            raise self.model.DoesNotExist

    def past(self, date=None):
        date = date or datetime.date.today()
        return self.filter(date__lt=date).order_by('date')


class MeetupType(models.Model):
    name = models.CharField(max_length=64)
    slug = models.SlugField()
    has_agenda = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class MeetupSponsorThrough(models.Model):
    class Meta:
        db_table = "meetups_meetup_sponsors"
        ordering = ["order"]

    meetup = models.ForeignKey("Meetup", on_delete=models.CASCADE, related_name="meetup_sponsors")
    sponsor = models.ForeignKey("Sponsor", on_delete=models.CASCADE, related_name="meetup_sponsors")

    meetup_description = models.TextField(blank=True, help_text="")

    order = models.PositiveIntegerField()

    def __str__(self):
        return self.sponsor.name

    @property
    def name(self):
        return self.sponsor.name

    @property
    def website(self):
        return self.sponsor.website

    @property
    def logo(self):
        return self.sponsor.logo

    @property
    def description(self):
        return self.sponsor.description

    @property
    def description_md(self):
        return self.sponsor.description_md

    @property
    def meetup_description_md(self):
        return mark_safe(markdown(escape(self.meetup_description)))


class Meetup(models.Model):
    meetup_type = models.ForeignKey(
        MeetupType,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
    )
    description = models.TextField(blank=True)
    number = models.PositiveIntegerField()
    date = models.DateTimeField()
    sponsors = models.ManyToManyField(
        Sponsor,
        related_name='sponsored_meetups',
        blank=True,
        through=MeetupSponsorThrough
    )
    venue = models.ForeignKey(
        Venue,
        related_name='meetups',
        on_delete=models.CASCADE,
        blank=True,
        null=True,
    )
    is_ready = models.BooleanField(default=False)
    date_modified = models.DateTimeField(auto_now=True)
    meetup_url = models.URLField(blank=True)
    video_url = models.URLField(blank=True)

    objects = MeetupManager()

    class Meta:
        ordering = ['-date']

    @property
    def description_md(self):
        return mark_safe(markdown(self.description))

    def __str__(self):
        name = settings.CONSTANT['GROUP_NAME']
        if self.meetup_type:
            name = self.meetup_type.name
        return '{0} #{1}'.format(name, self.number)

    def get_absolute_url(self):
        return reverse('meetups:meetup_detail', kwargs={
            'meetup_type': self.meetup_type.slug,
            'number': self.number
        })


class Speaker(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    website = models.URLField(blank=True)
    photo = models.ImageField(
        upload_to=SlugifyUploadTo(settings.SPEAKER_PHOTOS_DIR, ['first_name', 'last_name']),
        blank=True,
    )
    phone = models.CharField(max_length=30, blank=True)
    email = models.EmailField(blank=True)
    discord_handle = models.CharField(blank=True, max_length=64)
    slack_handle = models.CharField(blank=True, max_length=64)
    biography = models.TextField(blank=True)

    @property
    def biography_md(self):
        return mark_safe(markdown(escape(self.biography)))

    def __str__(self):
        return '{} {}'.format(self.first_name, self.last_name)

    class Meta:
        ordering = ['first_name', 'last_name']


class Talk(models.Model):
    LANGUAGES = (
        ('pl', 'Polish'),
        ('en', 'English'),
    )

    title = models.CharField(max_length=1000)
    description = models.TextField(blank=True)
    speakers = models.ManyToManyField(Speaker, related_name='talks')
    meetup = models.ForeignKey(
        Meetup,
        related_name='talks',
        blank=True,
        null=True,
        on_delete=models.CASCADE,
    )
    order = models.PositiveSmallIntegerField(null=True)
    slides_file = models.FileField(
        upload_to=SlugifyUploadTo(settings.SLIDES_FILES_DIR, ['meetup', 'title']),
        blank=True,
        max_length=500,
    )
    slides_url = models.URLField(blank=True)
    video_url = models.URLField(blank=True)
    language = models.CharField(choices=LANGUAGES, default='pl', max_length=2)
    without_owner = models.BooleanField(default=False)

    @property
    def description_md(self):
        return mark_safe(markdown(escape(self.description)))

    class Meta:
        ordering = ['order']

    def __str__(self):
        return self.title


class ExternalLink(models.Model):
    EXTERNAL_LINK_TYPES = (
        ('photos', 'Photos'),
        ('article', 'Article'),
        ('other', 'Other'),
    )

    meetup = models.ForeignKey(
        Meetup,
        related_name='external_links',
        on_delete=models.CASCADE,
    )
    url = models.URLField()
    type = models.CharField(max_length=10, choices=EXTERNAL_LINK_TYPES)
    description = models.TextField(blank=True)

    def __str__(self):
        return '{} ({})'.format(self.url, self.meetup)


class TalkProposal(models.Model):
    talk = models.OneToOneField(Talk, on_delete=models.CASCADE, related_name="proposal")
    message = models.TextField(blank=True)
    date_submitted = models.DateTimeField(auto_now_add=True)

    @property
    def message_md(self):
        return mark_safe(markdown(escape(self.message)))

    def __str__(self):
        return 'Proposal: {}'.format(self.talk)

meetpy/meetups/forms.py
from django_recaptcha.fields import ReCaptchaField
from django import forms
from django.conf import settings
from django.core.exceptions import ValidationError

from . import models
from .models import Talk


class TalkProposalForm(forms.ModelForm):
    talk_title = forms.CharField()
    talk_description = forms.CharField(max_length=1000, widget=forms.Textarea)
    talk_language = forms.ChoiceField(choices=Talk.LANGUAGES)
    speaker = forms.ModelChoiceField(
        queryset=models.Speaker.objects.filter(talks__meetup__isnull=False).distinct(),
        required=False,
    )
    speaker_first_name = forms.CharField(required=False, max_length=30)
    speaker_last_name = forms.CharField(required=False, max_length=30)
    speaker_website = forms.URLField(required=False)
    speaker_phone = forms.CharField(required=False, max_length=30)
    speaker_email = forms.EmailField(required=False)
    speaker_discord_handle = forms.CharField(required=False, max_length=64)
    speaker_slack_handle = forms.CharField(required=False, max_length=64)
    speaker_biography = forms.CharField(required=False, widget=forms.Textarea)
    speaker_photo = forms.ImageField(required=False)
    without_owner = forms.BooleanField(required=False, initial=False)

    if settings.RECAPTCHA_ENABLED:
        captcha = ReCaptchaField()

    REQUIRED_SPEAKER_FIELDS = [
        'speaker_first_name',
        'speaker_last_name',
        'speaker_phone',
        'speaker_email',
        'speaker_biography',
        'speaker_photo',
    ]

    class Meta:
        model = models.TalkProposal
        fields = ('message',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["talk_description"].widget.attrs["class"] = "wysiwygEditor"
        self.fields["speaker_biography"].widget.attrs["class"] = "wysiwygEditor"
        self.fields["message"].widget.attrs["class"] = "wysiwygEditor"

    def save(self, *args, **kwargs):
        talk_proposal = super().save(commit=False)
        talk = models.Talk.objects.create(
            title=self.cleaned_data['talk_title'],
            description=self.cleaned_data['talk_description'],
            language=self.cleaned_data["talk_language"],
        )
        if self.cleaned_data['speaker']:
            speaker = self.cleaned_data['speaker']
        else:
            speaker = models.Speaker.objects.create(
                first_name=self.cleaned_data['speaker_first_name'],
                last_name=self.cleaned_data['speaker_last_name'],
                website=self.cleaned_data['speaker_website'],
                phone=self.cleaned_data['speaker_phone'],
                email=self.cleaned_data['speaker_email'],
                discord_handle=self.cleaned_data['speaker_discord_handle'],
                slack_handle=self.cleaned_data['speaker_slack_handle'],
                biography=self.cleaned_data['speaker_biography'],
                photo=self.cleaned_data['speaker_photo'],
            )
        talk.speakers.add(speaker)
        talk_proposal.talk = talk
        talk_proposal.save()
        return talk_proposal

    def clean(self):
        if self.cleaned_data['without_owner'] is False and self._existing_speaker_field_empty():
            if self._all_required_new_speaker_fields_empty():
                raise ValidationError(settings.CONSTANT['EITHER_EXISTING_OR_NEW_SPEAKER_ERROR'])
            elif not self._all_required_new_speaker_fields_empty():
                for field_name in self.REQUIRED_SPEAKER_FIELDS:
                    if self.cleaned_data.get(field_name) in ['', None]:
                        self._errors[field_name] = self.fields[field_name].error_messages['required']
        return self.cleaned_data

    def _all_required_new_speaker_fields_empty(self):
        return all(self.cleaned_data.get(field_name) == '' for field_name in self.REQUIRED_SPEAKER_FIELDS)

    def _existing_speaker_field_empty(self):
        return not self.cleaned_data['speaker']

meetpy/templates/meetups/meetup_detail.html
{% extends "base.html" %}

{% load embed_video_tags %}
{% load static %}

{% block title %}{{ meetup }} - {{ meetup.date|date:"d.m.Y" }}{% endblock %}

{% block og_title %}{{ meetup }} - {{ meetup.date|date:"d.m.Y" }}{% endblock %}

{% block css %}
<link href="{% static 'css/bootstrap-image-gallery.css' %}" rel="stylesheet">
{% endblock %}

{% block js %}
<script type="text/javascript" src="{% static 'js/load-image.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap-image-gallery.js' %}"></script>
{% include 'includes/maps_api_script.html' with canvas_id='map-canvas' latitude=meetup.venue.latitude longitude=meetup.venue.longitude %}
{% endblock %}

{% block content %}
<div class="container" itemscope itemtype="http://schema.org/Event">
    <div class="row">
        <div class="span2 img-tip">
            <div class="line-orange"></div>
        </div>
        <div class="span6">
            <h1 itemprop="name">{{ meetup }}</h1>
        </div>
        <div class="pull-right">
            <a href="{% url 'meetups:meetup_list' %}" class="button button-block span3"> &laquo; LISTA SPOTKAŃ</a>
        </div>
    </div>
    <div class="row">
        <div class="span5 offset2">
            <h4 class="date" itemprop="startDate" content="{{ meetup.date|date:"c" }}"><span class="day">{{ meetup.date|date:"l" }}, </span>{{ meetup.date|date:"d.m.Y" }} <span class="pull-right"><i class="icon-clock"></i> {{ meetup.date|date:"H:i" }}</span></h4>
        </div>
        {% if meetup.meetup_url %}
          <div class="pull-right">
              <a href="{{ meetup.meetup_url }}" target="_blank" class="button button-block button-meetup span3">Dołącz na Meetupie</a>
          </div>
        {% endif %}
    </div>
    <div class="row margin-top-big">
        <div class="offset2 span10">
            <div class="media">
              {{ meetup.description_md }}
            </div>
          {% if meetup.video_url %}
            <div class="video-meetup-details">
              {% video meetup.video_url '780x440' is_secure=True %}
            </div>
          {% endif %}
            {% if meetup.meetup_type.has_agenda %}
              {% for talk in meetup.talks.all %}
              <div class="media meetup-talk" id="talk-{{ talk.title|slugify }}" itemprop="subEvent" itemscope itemtype="http://schema.org/Event">
                  <div class="media-body">
                      <h5>
                          {% for speaker in talk.speakers.all %}
                          <a href="#speaker-{{ speaker|slugify }}">{{ speaker }}</a>{% if not forloop.last %}, {% endif %}
                          {% endfor %}
                      </h5>
                      <h3>
                        <span itemprop="name">{{ talk.title }}</span>
                        <span class="lang-icon"><img src="{% get_static_prefix %}img/languages/{{ talk.language }}.png" alt="{{ talk.get_language_display }}"></span>
                          {% if talk.slides_url or talk.slides_file %}
                        <a href="{% if talk.slides_url %}{{ talk.slides_url }}{% else %}{{ talk.slides_file.url }}{% endif %}" target="_blank"><img src="{% static 'img/download.png' %}" alt="Link do prezentacji"></a>
                          {% endif %}
                      </h3>
                      <div itemprop="description">{{ talk.description_md }}</div>
                  </div>
                  {% if talk.video_url %}
                    <div class="video-meetup-details">
                      {% video talk.video_url '780x440' is_secure=True %}
                    </div>
                  {% endif %}

              </div>
              {% endfor %}
              {% if not meetup.is_ready %}
              <div class="more-info">
                <h3>agenda w przygotowaniu</h3>
              </div>
              {% endif %}
            {% endif %}
        </div>
    </div>
    {% if meetup.meetup_type.has_agenda %}
      <div class="row margin-top-big">
          <div class="span2 img-tip">
              <img src="{% static 'img/user.png' %}" alt="Prelegenci">
          </div>
          <div class="span10">
              <h2>Prelegenci</h2>
              {% for talk in meetup.talks.all %}
              {% for speaker in talk.speakers.all %}
              <div class="media" id="speaker-{{ speaker|slugify }}" itemprop="performer" itemscope itemtype="http://schema.org/Person">
                <div class="pull-left img-user-container hidden-phone">
                    <img src="{% if speaker.photo %}{{ speaker.photo.url }}{% else %}{% static 'img/avatar.png' %}{% endif %}" alt="Zdjecie {{ speaker }}" class="img-user" itemprop="image"><br>
                  </div>
                  <div class="media-body">
                      <h3>
                          <span itemprop="name">{{ speaker }}</span>{% if speaker.website %} <a href="{{ speaker.website }}" target="_blank"><img src="{% static 'img/link.png' %}" alt="Strona prelegenta" class="speaker-link"></a>{% endif %}
                      </h3>
                      <div itemprop="description">{{ speaker.biography_md }}</div>
                  </div>
              </div>
              {% endfor %}
              {% empty %}
              <p>Agenda w przygotowaniu. Masz pomysł na prezentację? Zobacz <a href="{% url 'meetups:speaker_list' %}#be-speaker">jak zostać prelegentem.</a></p>
              {% endfor %}
          </div>
      </div>
    {% endif %}
    {% if meetup.external_links.exists %}
    <div class="row margin-top-big">
        <div class="span2 img-tip">
            <img src="{% static 'img/links.png' %}" alt="Linki">
        </div>
        <div class="span10">
            <h2>Linki</h2>
            <ul>
                {% for external_link in meetup.external_links.all %}
                <li><a href="{{ external_link.url }}" target="_blank" class="{{ external_link.type }}">{{ external_link.url }}</a> - {{ external_link.description }}</li>
                {% endfor %}
            </ul>
        </div>
    </div>
    {% endif %}
    {% if meetup.sponsors.exists %}
    <div class="row margin-top-big">
        <div class="span2 img-tip">
            <img src="{% static 'img/sponsors.jpg' %}" alt="Sponsorzy">
        </div>
        <div class="span10">
            <h2>Sponsorzy spotkania</h2>
            {% for sponsor in meetup.meetup_sponsors.all %}
            <div class="media">
                <div class="media-body">
                    <a href="{{ sponsor.website }}" target="_blank" class="no-hover"><img class="img-sponsors" src="{{ sponsor.logo.url }}" alt="{{ sponsor.name }}"></a>
                    {{ sponsor.description_md }}
                    {{ sponsor.meetup_description_md }}
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    {% endif %}
    {% if meetup.venue %}
    <div class="row margin-top-big margin-bottom-large">
        <div class="span2 img-tip">
            <img src="{% static 'img/location.jpg' %}" alt="Lokalizacja">
        </div>
        <div class="span10" itemscope itemprop="location" itemtype="http://schema.org/Place">
            <h2>Lokalizacja</h2>
            <h4 class="weight-normal"><img src="{% static 'img/location.png' %}" alt="Lokalizacja" class="icon-location"> <span itemprop="name">{{ meetup.venue.name }}</span>, <span itemprop="address">{{ meetup.venue.address }}</span></h4>
            <div class="margin-top-normal" itemprop="geo" itemscope itemtype="http://schema.org/GeoCoordinates">
	            <div id="map-canvas"></div>
                <meta itemprop="latitude" content="{{ meetup.venue.latitude }}">
                <meta itemprop="longitude" content="{{ meetup.venue.longitude }}">
            </div>
        </div>
    </div>
    {% endif %}
</div>

<div id="modal-gallery" class="modal modal-gallery hide fade" data-animation="false" tabindex="-1">
    <div class="modal-header">
        <a class="close" data-dismiss="modal">&times;</a>
        <h3 class="modal-title"></h3>
    </div>
    <div class="modal-body"><div class="modal-image"></div></div>
</div>

{% endblock %}

meetpy/templates/meetups/meetup_list.html
{% extends "base_content.html" %}

{% load embed_video_tags %}

{% block title %}Spotkania{% endblock %}

{% block og_title %}Spotkania{% endblock %}

{% block subcontent %}
<h1>Spotkania</h1>
{% for meetup in object_list %}
{% include "meetups/includes/meetup_on_list.html" %}
{% endfor %}
{% endblock %}

meetpy/templates/meetups/meetup_promo.html
{% extends "base.html" %}

{% load static %}

{% block title %}{{ meetup }} promo{% endblock %}

{% block og_title %}{{ meetup }} promo{% endblock %}

{% block content %}
<div class="container" itemscope itemtype="http://schema.org/Event">
    <div class="row">
        <div class="span2 img-tip">
            <div class="line-orange"></div>
        </div>
        <div class="span8">
            <h1 itemprop="name">{{ object }} promo</h1>
        </div>
    </div>
    <div class="row margin-top-big">
        <div class="offset2 span10">
            {% include 'meetups/promos/meetup.html' %}
        </div>
    </div>
    <div class="row margin-top-big">
        <div class="offset2 span10">
            {% include 'meetups/promos/facebook.html' %}
        </div>
    </div>
    <div class="row margin-top-big">
        <div class="offset2 span10">
            {% include 'meetups/promos/youtube.html' %}
        </div>
    </div>
    <div class="row margin-top-big">
    </div>
</div>

{% endblock %}

meetpy/templates/meetups/search_results.html
{% extends "base_content.html" %}

<form method="GET" action=''>
<input type='text' name='q' placeholder='Search posts' value='{{ request.GET.q }}'/>
<input type='submit' value='Search' />

{% block searchresults %}
Wyniki
{% endblock %}


{% block content %}
{% for s in search %}
{% if s.title %}
<p>{{ s.title }}</p>
{% endif %}
{% if s.description %}
<p>{{ s.description }}</p>
{% endif %}
{% if s.biography %}
<p>{{ s.biography }}</p>
{% endif %}
{% endfor %}
{% endblock %}

meetpy/templates/meetups/speaker_list.html
{% extends "base_content.html" %}

{% load static %}

{% block title %}Prelegenci{% endblock %}

{% block og_title %}Prelegenci{% endblock %}

{% block subcontent %}
    <div class="margin-bottom-large">
    <h1>Prelegenci</h1>
        <div class="row">
            <div class="media speaker-list">
                <ul>
                    {% for speaker in object_list %}
                    <li id="speaker-{{ speaker.id }}">
                        <div class="pull-left img-user-container hidden-phone">
                            <img  src="{% if speaker.photo %}{{ speaker.photo.url }}{% else %}{% static 'img/avatar.png' %}{% endif %}" alt="Zdjecie {{ speaker }}" class="img-user"><br>
                        </div>
                        <div class="media-body">
                            <h3>{{ speaker.first_name }} {{ speaker.last_name }}</h3>
                            {% if speaker.website %}<a href="{{ speaker.website }}" target="_blank" class="link-gray"><img src="{% static 'img/link.png' %}" alt="Strona prelegenta" class="speaker-link"></a>{% endif %}
                            {{ speaker.biography_md }}
                        </div>
                        <div class="clearfix"></div>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
{% endblock %}

meetpy/templates/meetups/talkproposal_form.html
{% extends 'base_content.html' %}
{% load static %}

{% block css %}
  <link rel="stylesheet" href="{% static "css/toastui-editor.min.css" %}" />
{% endblock %}
{% block js %}
  <script src="{% static "js/toastui-editor-all.min.js" %}"></script>
  <script type="text/javascript" src="{% static "js/wysiwygEditor.js" %}"></script>
{% endblock %}
{% block title %}Zgłoszenie prezentacji{% endblock %}

{% block subcontent %}
    <div class="margin-bottom-large">
        <h1>Zgłoś swoją prelekcję</h1>
        <p>
            Chcesz zostać prelegentem podczas jednego z naszych spotkań? Nic prostszego! Wystarczy wypełnić poniższy formularz
            i poczekać na naszę odpowiedź.
        </p>
    </div>
    <div class="row margin-bottom-large">
        <div class="span8">
            <form method="POST" novalidate enctype="multipart/form-data">{% csrf_token %}
                <h2>Prelekcja</h2>
                {% include "meetups/includes/form_input.html" with field=form.talk_title label='Tytuł' %}
                {% include "meetups/includes/form_input.html" with field=form.talk_language label='Język' %}
                {% include "meetups/includes/form_input.html" with field=form.talk_description label='Opis' %}
                <h2 class="margin-top-normal">Prelegent</h2>
                <p>
                    Jeżeli byłeś już kiedyś prelegentem na spotkaniu {{ group.name }} wystarczy, że znajdziesz siebie na poniższej liście.
                    W przeciwnym wypadku musisz wypełnić wszystkie pozostałe pola.
                </p>
                <div class="control-group error">
                    <div class="controls">
                        <span class="help-inline">{{ form.non_field_errors }}</span>
                    </div>
                </div>
                {% include "meetups/includes/form_input.html" with field=form.speaker %}
                <div id="speakers-inputs">
                {% include "meetups/includes/form_input.html" with field=form.speaker_first_name label='Imię' %}
                {% include "meetups/includes/form_input.html" with field=form.speaker_last_name label='Nazwisko' %}
                {% include "meetups/includes/form_input.html" with field=form.speaker_biography label='Biogram' %}
                {% include "meetups/includes/form_input.html" with field=form.speaker_website label='Strona WWW' %}
                {% include "meetups/includes/form_input.html" with field=form.speaker_photo label='Zdjęcie' %}
                {% include "meetups/includes/form_input.html" with field=form.speaker_phone label='Numer telefonu' %}
                {% include "meetups/includes/form_input.html" with field=form.speaker_email label='E-mail' %}
                {% if group.social.discord %}
                  {% include "meetups/includes/form_input.html" with field=form.speaker_discord_handle label='Nick/handle na discordzie' %}
                {% endif %}
                {% if group.social.slack %}
                  {% include "meetups/includes/form_input.html" with field=form.speaker_slack_handle label='Nick/handle na slacku' %}
                {% endif %}
		{% include "meetups/includes/form_input.html" with field=form.without_owner label='Bez prelegenta' %}
                </div>
                <h2 class="margin-top-normal">Dodatkowe uwagi</h2>
                <p>
                    W tym polu powinny znaleźć się wszystkie dodatkowe uwagi dotyczące Twojej prelekcji, np. wymagania
                    sprzętowe, planowana data lub numer spotkania na którym chcesz wygłosić prelekcję, etc.
                </p>
                {% include "meetups/includes/form_input.html" with field=form.message %}
                {% if form.captcha %}
                  {% include "meetups/includes/form_input.html" with field=form.captcha %}
                {% endif %}
                <input type="submit" class="button button-block button--submit pull-right margin-top-normal" value="Wyślij zgłoszenie">
            </form>
        </div>
    </div>
    <script>
        $(document).ready(function () {
           var toggleSpeakerInputs = function () {
               var hasVal = $('#id_speaker').val() !== "";
               if (hasVal) {
                   $('#speakers-inputs').slideUp();
               } else {
                   $('#speakers-inputs').slideDown();
               }
           };

           $('#id_speaker').change(toggleSpeakerInputs);

           toggleSpeakerInputs();
        });
    </script>
{% endblock %}